CREATE TABLE BOARD (
	IDX INT NOT NULL AUTO_INCREMENT,
	TITLE VARCHAR(1000) NOT NULL,
	CONTENT VARCHAR(2000) NOT NULL,
	WRITER VARCHAR(100) NOT NULL,
	INDATE DATETIME DEFAULT NOW(),
	COUNT INT DEFAULT 0,
	PRIMARY KEY(IDX)
);

/* INSERT DATA */

INSERT INTO BOARD(TITLE, CONTENT, WRITER) VALUES
("WHAT FOR LUNCH","CHICKEN OR SALMON","MIR"),
("SHELL SCRIPT","use the Terminal for direct control or the Finder for a quick double-click execution.","MOOMIN"),
("MERRY CHRISTMAS","I WANT TO GET NEW CAT TOWER.","MIR"),
("HATE MEDICAL CHECK","ULTRA SOUND CHECK MADE ME NAKED...","KKOMI");

COMMIT;

SELECT * FROM BOARD;
/* DELETE */
DELETE FROM BOARD WHERE WRITER = 'TESTER';
/* UPDATE */
UPDATE BOARD 
SET TITLE = 'MAC OS CLI', CONTENTC = 'GOOD JOB!' 
WHERE WRITER = 'MOOMIN';

/* INCREMENT COUNT*/
UPDATE BOARD
SET COUNT = COUNT +1
WHERE IDX = 5;


DELETE FROM BOARD;

COMMIT;

ALTER TABLE BOARD ADD ID VARCHAR(100) NOT NULL;
ALTER TABLE BOARD ADD FILEPATH VARCHAR(200);
