SELECT * FROM WEB_BOARD

INSERT INTO WEB_BOARD(CONTENT, WRITER,TITLE) VALUES("THE DAY IS COMING... WHAT THE HECK WITH MY G KEY...","MIR ISAAC KIM","D-1 BABAHM"),
("CONTENT CONTENT CONTENT", "TITLE, TITLE","AUTHOR"),
("I AM JUST A LIL BIT CAUGHT IN THE MIDDLE LIFE IS A MAZE","THE SHOW","SINGER");

COMMIT;